Fix KeyError on .egg-info files in debian directory
Apport fails to build:

```
$ python3.11 setup.py install --root=debian/tmp --install-layout=deb
[...]
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/setup.py", line 170, in <module>
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 90, in setup
    src.remove(f)
KeyError: 'debian/tmp/usr/lib/python3.11/dist-packages/apport-2.25.0.egg-info/PKG-INFO'
```

This is caused by the for loop to remove
`debian/tmp/usr/lib/python3.11/dist-packages/apport-2.25.0.egg-info/PKG-INFO`
twice: Once because the file is in the `debian` directory and second
because it has `.egg-info/` in its name.

Signed-off-by: Benjamin Drung <benjamin.drung@canonical.com>